$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: viral-prediction-endpoint
model: azureml:bert-viral-classifier:1
code_configuration:
  code: .
  scoring_script: score.py
environment:
  conda_file: inference-env.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
instance_type: Standard_DS2_v2
instance_count: 1
